import { configApp } from "@adonisjs/eslint-config"; // Import the base ESLint configuration factory from AdonisJS.
export default configApp(); // Export the default configuration generated by AdonisJS.
